rails:
  build: .
  command:
    [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
  mem_limit: 384m
  environment:
    DISABLE_SPRING: "1"
  ports:
    - "3000:3000"
  volumes:
    - ".:/usr/src/app"
  links:
    - "mysql"
    - "redis"

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: "passwd"

redis:
  image: redis:alpine
  ports:
    - 6379:6379
  volumes:
    - ./tmp/redis:/data
  command: redis-server --appendonly yes
